---
pi_hostname: "nil"
home_dir: "/home/{{ vault_pi_user }}"
svc_dir: "/home/{{ vault_pi_user }}/svc"
docker_gid: 985

stacks:
  - name: ingress
    profile: prod
    caddy: true
  - name: sea-battle
    profile: prod
    deploy: true
    caddy: true
  - name: got
    profile: prod
    deploy: true
  - name: gh-stats
    profile: prod
    deploy: true
    caddy: true
  - name: githuber
    profile: prod
    deploy: true
  - name: pimon
    profile: prod
    deploy: true
  - name: jarvis
    profile: prod
    deploy: true
  - name: executor
    profile: prod
    deploy: true
  - name: streamtower
    profile: prod
    deploy: true
