---
all:
  children:
    routers:
      hosts:
        gl-mt6000:
          ansible_host: 192.168.8.1
          ansible_user: "{{ vault_router_user }}"
          ansible_password: "{{ vault_router_password }}"

    raspberry_pis:
      hosts:
        nil:
          ansible_host: [REDACTED]
          ansible_user: "{{ vault_pi_user }}"
          ansible_password: "{{ vault_pi_password }}"
          ansible_become: true
          ansible_become_password: "{{ vault_pi_password }}"
