services:
  vaultwarden:
    profiles: ["prod"]
    image: vaultwarden/server:latest
    environment:
      - DOMAIN=${DOMAIN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED:-false}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - data:/data
    restart: unless-stopped
    networks:
      - default
      - ingress

volumes:
  data:

networks:
  ingress:
    external: true
